#include "psc.h"
#include "gpio.h"

#include <ti/pspiom/cslr/cslr.h>
#include <ti/pspiom/cslr/soc_OMAPL138.h>
#include <ti/pspiom/cslr/cslr_syscfg0_OMAPL138.h>
#include <ti/pspiom/cslr/cslr_gpio.h>

CSL_SyscfgRegsOvly SysCfgRegs  = (CSL_SyscfgRegsOvly)CSL_SYSCFG_0_REGS;
CSL_GpioRegsOvly GpioRegs = (CSL_GpioRegsOvly)CSL_GPIO_0_REGS;


const GPIO_PINMUX_DESCRIPTOR GPIO_PINMUX_BANK0[NUM_GPIO_PINS] = 
{
	{	PINMUX1_ADDR,		CSL_SYSCFG_PINMUX1_PINMUX1_31_28_SHIFT	},
	{	PINMUX1_ADDR,		CSL_SYSCFG_PINMUX1_PINMUX1_27_24_SHIFT	},
	{	PINMUX1_ADDR,		CSL_SYSCFG_PINMUX1_PINMUX1_23_20_SHIFT	},
	{	PINMUX1_ADDR,		CSL_SYSCFG_PINMUX1_PINMUX1_19_16_SHIFT	},
	{	PINMUX1_ADDR,		CSL_SYSCFG_PINMUX1_PINMUX1_15_12_SHIFT	},
	{	PINMUX1_ADDR,		CSL_SYSCFG_PINMUX1_PINMUX1_11_8_SHIFT	},
	{	PINMUX1_ADDR,		CSL_SYSCFG_PINMUX1_PINMUX1_7_4_SHIFT	},
	{	PINMUX1_ADDR,		CSL_SYSCFG_PINMUX1_PINMUX1_3_0_SHIFT	},
	{	PINMUX0_ADDR,		CSL_SYSCFG_PINMUX0_PINMUX0_31_28_SHIFT	},
	{	PINMUX0_ADDR,		CSL_SYSCFG_PINMUX0_PINMUX0_27_24_SHIFT	},
	{	PINMUX0_ADDR,		CSL_SYSCFG_PINMUX0_PINMUX0_23_20_SHIFT	},
	{	PINMUX0_ADDR,		CSL_SYSCFG_PINMUX0_PINMUX0_19_16_SHIFT	},
	{	PINMUX0_ADDR,		CSL_SYSCFG_PINMUX0_PINMUX0_15_12_SHIFT	},
	{	PINMUX0_ADDR,		CSL_SYSCFG_PINMUX0_PINMUX0_11_8_SHIFT	},
	{	PINMUX0_ADDR,		CSL_SYSCFG_PINMUX0_PINMUX0_7_4_SHIFT	},
	{	PINMUX0_ADDR,		CSL_SYSCFG_PINMUX0_PINMUX0_3_0_SHIFT	},
};

const GPIO_PINMUX_DESCRIPTOR GPIO_PINMUX_BANK1[NUM_GPIO_PINS] = 
{
	{	PINMUX4_ADDR,		CSL_SYSCFG_PINMUX4_PINMUX4_31_28_SHIFT	},
	{	PINMUX4_ADDR,		CSL_SYSCFG_PINMUX4_PINMUX4_27_24_SHIFT	},
	{	PINMUX4_ADDR,		CSL_SYSCFG_PINMUX4_PINMUX4_23_20_SHIFT	},
	{	PINMUX4_ADDR,		CSL_SYSCFG_PINMUX4_PINMUX4_19_16_SHIFT	},
	{	PINMUX4_ADDR,		CSL_SYSCFG_PINMUX4_PINMUX4_15_12_SHIFT	},
	{	PINMUX4_ADDR,		CSL_SYSCFG_PINMUX4_PINMUX4_11_8_SHIFT	},
	{	PINMUX4_ADDR,		CSL_SYSCFG_PINMUX4_PINMUX4_7_4_SHIFT	},
	{	PINMUX4_ADDR,		CSL_SYSCFG_PINMUX4_PINMUX4_3_0_SHIFT	},
	{	PINMUX3_ADDR,		CSL_SYSCFG_PINMUX3_PINMUX3_3_0_SHIFT	},
	{	PINMUX2_ADDR,		CSL_SYSCFG_PINMUX2_PINMUX2_27_24_SHIFT	},
	{	PINMUX2_ADDR,		CSL_SYSCFG_PINMUX2_PINMUX2_23_20_SHIFT	},
	{	PINMUX2_ADDR,		CSL_SYSCFG_PINMUX2_PINMUX2_19_16_SHIFT	},
	{	PINMUX2_ADDR,		CSL_SYSCFG_PINMUX2_PINMUX2_15_12_SHIFT	},
	{	PINMUX2_ADDR,		CSL_SYSCFG_PINMUX2_PINMUX2_11_8_SHIFT	},
	{	PINMUX2_ADDR,		CSL_SYSCFG_PINMUX2_PINMUX2_7_4_SHIFT	},
	{	PINMUX2_ADDR,		CSL_SYSCFG_PINMUX2_PINMUX2_3_0_SHIFT	},
};

const GPIO_PINMUX_DESCRIPTOR GPIO_PINMUX_BANK2[NUM_GPIO_PINS] = 
{
	{	PINMUX6_ADDR,		CSL_SYSCFG_PINMUX6_PINMUX6_31_28_SHIFT	},
	{	PINMUX6_ADDR,		CSL_SYSCFG_PINMUX6_PINMUX6_27_24_SHIFT	},
	{	PINMUX6_ADDR,		CSL_SYSCFG_PINMUX6_PINMUX6_23_20_SHIFT	},
	{	PINMUX6_ADDR,		CSL_SYSCFG_PINMUX6_PINMUX6_19_16_SHIFT	},
	{	PINMUX6_ADDR,		CSL_SYSCFG_PINMUX6_PINMUX6_15_12_SHIFT	},
	{	PINMUX6_ADDR,		CSL_SYSCFG_PINMUX6_PINMUX6_11_8_SHIFT	},
	{	PINMUX6_ADDR,		CSL_SYSCFG_PINMUX6_PINMUX6_7_4_SHIFT	},
	{	PINMUX6_ADDR,		CSL_SYSCFG_PINMUX6_PINMUX6_3_0_SHIFT	},
	{	PINMUX5_ADDR,		CSL_SYSCFG_PINMUX5_PINMUX5_31_28_SHIFT	},
	{	PINMUX5_ADDR,		CSL_SYSCFG_PINMUX5_PINMUX5_27_24_SHIFT	},
	{	PINMUX5_ADDR,		CSL_SYSCFG_PINMUX5_PINMUX5_23_20_SHIFT	},
	{	PINMUX5_ADDR,		CSL_SYSCFG_PINMUX5_PINMUX5_19_16_SHIFT	},
	{	PINMUX5_ADDR,		CSL_SYSCFG_PINMUX5_PINMUX5_15_12_SHIFT	},
	{	PINMUX5_ADDR,		CSL_SYSCFG_PINMUX5_PINMUX5_11_8_SHIFT	},
	{	PINMUX5_ADDR,		CSL_SYSCFG_PINMUX5_PINMUX5_7_4_SHIFT	},
	{	PINMUX5_ADDR,		CSL_SYSCFG_PINMUX5_PINMUX5_3_0_SHIFT	},
};

const GPIO_PINMUX_DESCRIPTOR GPIO_PINMUX_BANK3[NUM_GPIO_PINS] = 
{
	{	PINMUX8_ADDR,		CSL_SYSCFG_PINMUX8_PINMUX8_31_28_SHIFT	},
	{	PINMUX8_ADDR,		CSL_SYSCFG_PINMUX8_PINMUX8_27_24_SHIFT	},
	{	PINMUX8_ADDR,		CSL_SYSCFG_PINMUX8_PINMUX8_23_20_SHIFT	},
	{	PINMUX8_ADDR,		CSL_SYSCFG_PINMUX8_PINMUX8_19_16_SHIFT	},
	{	PINMUX8_ADDR,		CSL_SYSCFG_PINMUX8_PINMUX8_15_12_SHIFT	},
	{	PINMUX8_ADDR,		CSL_SYSCFG_PINMUX8_PINMUX8_11_8_SHIFT	},
	{	PINMUX8_ADDR,		CSL_SYSCFG_PINMUX8_PINMUX8_7_4_SHIFT	},
	{	PINMUX8_ADDR,		CSL_SYSCFG_PINMUX8_PINMUX8_3_0_SHIFT	},
	{	PINMUX7_ADDR,		CSL_SYSCFG_PINMUX7_PINMUX7_31_28_SHIFT	},
	{	PINMUX7_ADDR,		CSL_SYSCFG_PINMUX7_PINMUX7_27_24_SHIFT	},
	{	PINMUX7_ADDR,		CSL_SYSCFG_PINMUX7_PINMUX7_23_20_SHIFT	},
	{	PINMUX7_ADDR,		CSL_SYSCFG_PINMUX7_PINMUX7_19_16_SHIFT	},
	{	PINMUX7_ADDR,		CSL_SYSCFG_PINMUX7_PINMUX7_15_12_SHIFT	},
	{	PINMUX7_ADDR,		CSL_SYSCFG_PINMUX7_PINMUX7_11_8_SHIFT	},
	{	PINMUX7_ADDR,		CSL_SYSCFG_PINMUX7_PINMUX7_7_4_SHIFT	},
	{	PINMUX7_ADDR,		CSL_SYSCFG_PINMUX7_PINMUX7_3_0_SHIFT	},
};

const GPIO_PINMUX_DESCRIPTOR GPIO_PINMUX_BANK4[NUM_GPIO_PINS] = 
{
	{	PINMUX10_ADDR,		CSL_SYSCFG_PINMUX10_PINMUX10_31_28_SHIFT	},
	{	PINMUX10_ADDR,		CSL_SYSCFG_PINMUX10_PINMUX10_27_24_SHIFT	},
	{	PINMUX10_ADDR,		CSL_SYSCFG_PINMUX10_PINMUX10_23_20_SHIFT	},
	{	PINMUX10_ADDR,		CSL_SYSCFG_PINMUX10_PINMUX10_19_16_SHIFT	},
	{	PINMUX10_ADDR,		CSL_SYSCFG_PINMUX10_PINMUX10_15_12_SHIFT	},
	{	PINMUX10_ADDR,		CSL_SYSCFG_PINMUX10_PINMUX10_11_8_SHIFT	},
	{	PINMUX10_ADDR,		CSL_SYSCFG_PINMUX10_PINMUX10_7_4_SHIFT	},
	{	PINMUX10_ADDR,		CSL_SYSCFG_PINMUX10_PINMUX10_3_0_SHIFT	},
	{	PINMUX9_ADDR,		CSL_SYSCFG_PINMUX9_PINMUX9_31_28_SHIFT	},
	{	PINMUX9_ADDR,		CSL_SYSCFG_PINMUX9_PINMUX9_27_24_SHIFT	},
	{	PINMUX9_ADDR,		CSL_SYSCFG_PINMUX9_PINMUX9_23_20_SHIFT	},
	{	PINMUX9_ADDR,		CSL_SYSCFG_PINMUX9_PINMUX9_19_16_SHIFT	},
	{	PINMUX9_ADDR,		CSL_SYSCFG_PINMUX9_PINMUX9_15_12_SHIFT	},
	{	PINMUX9_ADDR,		CSL_SYSCFG_PINMUX9_PINMUX9_11_8_SHIFT	},
	{	PINMUX9_ADDR,		CSL_SYSCFG_PINMUX9_PINMUX9_7_4_SHIFT	},
	{	PINMUX9_ADDR,		CSL_SYSCFG_PINMUX9_PINMUX9_3_0_SHIFT	},
};

const GPIO_PINMUX_DESCRIPTOR GPIO_PINMUX_BANK5[NUM_GPIO_PINS] = 
{
	{	PINMUX12_ADDR,		CSL_SYSCFG_PINMUX12_PINMUX12_31_28_SHIFT	},
	{	PINMUX12_ADDR,		CSL_SYSCFG_PINMUX12_PINMUX12_27_24_SHIFT	},
	{	PINMUX12_ADDR,		CSL_SYSCFG_PINMUX12_PINMUX12_23_20_SHIFT	},
	{	PINMUX12_ADDR,		CSL_SYSCFG_PINMUX12_PINMUX12_19_16_SHIFT	},
	{	PINMUX12_ADDR,		CSL_SYSCFG_PINMUX12_PINMUX12_15_12_SHIFT	},
	{	PINMUX12_ADDR,		CSL_SYSCFG_PINMUX12_PINMUX12_11_8_SHIFT	},
	{	PINMUX12_ADDR,		CSL_SYSCFG_PINMUX12_PINMUX12_7_4_SHIFT	},
	{	PINMUX12_ADDR,		CSL_SYSCFG_PINMUX12_PINMUX12_3_0_SHIFT	},
	{	PINMUX11_ADDR,		CSL_SYSCFG_PINMUX11_PINMUX11_31_28_SHIFT	},
	{	PINMUX11_ADDR,		CSL_SYSCFG_PINMUX11_PINMUX11_27_24_SHIFT	},
	{	PINMUX11_ADDR,		CSL_SYSCFG_PINMUX11_PINMUX11_23_20_SHIFT	},
	{	PINMUX11_ADDR,		CSL_SYSCFG_PINMUX11_PINMUX11_19_16_SHIFT	},
	{	PINMUX11_ADDR,		CSL_SYSCFG_PINMUX11_PINMUX11_15_12_SHIFT	},
	{	PINMUX11_ADDR,		CSL_SYSCFG_PINMUX11_PINMUX11_11_8_SHIFT	},
	{	PINMUX11_ADDR,		CSL_SYSCFG_PINMUX11_PINMUX11_7_4_SHIFT	},
	{	PINMUX11_ADDR,		CSL_SYSCFG_PINMUX11_PINMUX11_3_0_SHIFT	},
};

const GPIO_PINMUX_DESCRIPTOR GPIO_PINMUX_BANK6[NUM_GPIO_PINS] = 
{
	{	PINMUX19_ADDR,		CSL_SYSCFG_PINMUX19_PINMUX19_27_24_SHIFT	},
	{	PINMUX19_ADDR,		CSL_SYSCFG_PINMUX19_PINMUX19_23_20_SHIFT	},
	{	PINMUX19_ADDR,		CSL_SYSCFG_PINMUX19_PINMUX19_19_16_SHIFT	},
	{	PINMUX19_ADDR,		CSL_SYSCFG_PINMUX19_PINMUX19_15_12_SHIFT	},
	{	PINMUX19_ADDR,		CSL_SYSCFG_PINMUX19_PINMUX19_11_8_SHIFT	},
	{	PINMUX16_ADDR,		CSL_SYSCFG_PINMUX16_PINMUX16_7_4_SHIFT	},
	{	PINMUX14_ADDR,		CSL_SYSCFG_PINMUX14_PINMUX14_7_4_SHIFT	},
	{	PINMUX14_ADDR,		CSL_SYSCFG_PINMUX14_PINMUX14_3_0_SHIFT	},
	{	PINMUX13_ADDR,		CSL_SYSCFG_PINMUX13_PINMUX13_31_28_SHIFT	},
	{	PINMUX13_ADDR,		CSL_SYSCFG_PINMUX13_PINMUX13_27_24_SHIFT	},
	{	PINMUX13_ADDR,		CSL_SYSCFG_PINMUX13_PINMUX13_23_20_SHIFT	},
	{	PINMUX13_ADDR,		CSL_SYSCFG_PINMUX13_PINMUX13_19_16_SHIFT	},
	{	PINMUX13_ADDR,		CSL_SYSCFG_PINMUX13_PINMUX13_15_12_SHIFT	},
	{	PINMUX13_ADDR,		CSL_SYSCFG_PINMUX13_PINMUX13_11_8_SHIFT	},
	{	PINMUX13_ADDR,		CSL_SYSCFG_PINMUX13_PINMUX13_7_4_SHIFT	},
	{	PINMUX13_ADDR,		CSL_SYSCFG_PINMUX13_PINMUX13_3_0_SHIFT	},
};

const GPIO_PINMUX_DESCRIPTOR GPIO_PINMUX_BANK7[NUM_GPIO_PINS] = 
{
	{	PINMUX18_ADDR,		CSL_SYSCFG_PINMUX18_PINMUX18_7_4_SHIFT	},
	{	PINMUX18_ADDR,		CSL_SYSCFG_PINMUX18_PINMUX18_3_0_SHIFT	},
	{	PINMUX17_ADDR,		CSL_SYSCFG_PINMUX17_PINMUX17_31_28_SHIFT	},
	{	PINMUX17_ADDR,		CSL_SYSCFG_PINMUX17_PINMUX17_27_24_SHIFT	},
	{	PINMUX17_ADDR,		CSL_SYSCFG_PINMUX17_PINMUX17_23_20_SHIFT	},
	{	PINMUX17_ADDR,		CSL_SYSCFG_PINMUX17_PINMUX17_19_16_SHIFT	},
	{	PINMUX17_ADDR,		CSL_SYSCFG_PINMUX17_PINMUX17_15_12_SHIFT	},
	{	PINMUX17_ADDR,		CSL_SYSCFG_PINMUX17_PINMUX17_11_8_SHIFT	},
	{	PINMUX17_ADDR,		CSL_SYSCFG_PINMUX17_PINMUX17_7_4_SHIFT	},
	{	PINMUX17_ADDR,		CSL_SYSCFG_PINMUX17_PINMUX17_3_0_SHIFT	},
	{	PINMUX16_ADDR,		CSL_SYSCFG_PINMUX16_PINMUX16_31_28_SHIFT	},
	{	PINMUX16_ADDR,		CSL_SYSCFG_PINMUX16_PINMUX16_27_24_SHIFT	},
	{	PINMUX16_ADDR,		CSL_SYSCFG_PINMUX16_PINMUX16_23_20_SHIFT	},
	{	PINMUX16_ADDR,		CSL_SYSCFG_PINMUX16_PINMUX16_19_16_SHIFT	},
	{	PINMUX16_ADDR,		CSL_SYSCFG_PINMUX16_PINMUX16_15_12_SHIFT	},
	{	PINMUX16_ADDR,		CSL_SYSCFG_PINMUX16_PINMUX16_11_8_SHIFT	},
};

const GPIO_PINMUX_DESCRIPTOR GPIO_PINMUX_BANK8[NUM_GPIO_PINS] = 					// Unmapped bank. Verify datasheet before using
{
	{	PINMUX19_ADDR,		CSL_SYSCFG_PINMUX19_PINMUX19_31_28_SHIFT	},
	{	PINMUX3_ADDR,		CSL_SYSCFG_PINMUX3_PINMUX3_31_28_SHIFT	},
	{	PINMUX3_ADDR,		CSL_SYSCFG_PINMUX3_PINMUX3_27_24_SHIFT	},
	{	PINMUX3_ADDR,		CSL_SYSCFG_PINMUX3_PINMUX3_23_20_SHIFT	},
	{	PINMUX3_ADDR,		CSL_SYSCFG_PINMUX3_PINMUX3_19_16_SHIFT	},
	{	PINMUX3_ADDR,		CSL_SYSCFG_PINMUX3_PINMUX3_15_12_SHIFT	},
	{	PINMUX3_ADDR,		CSL_SYSCFG_PINMUX3_PINMUX3_11_8_SHIFT	},
	{	PINMUX2_ADDR,		CSL_SYSCFG_PINMUX2_PINMUX2_31_28_SHIFT	},
	{	PINMUX19_ADDR,		CSL_SYSCFG_PINMUX19_PINMUX19_7_4_SHIFT	},
	{	PINMUX19_ADDR,		CSL_SYSCFG_PINMUX19_PINMUX19_3_0_SHIFT	},
	{	PINMUX18_ADDR,		CSL_SYSCFG_PINMUX18_PINMUX18_31_28_SHIFT	},
	{	PINMUX18_ADDR,		CSL_SYSCFG_PINMUX18_PINMUX18_27_24_SHIFT	},
	{	PINMUX18_ADDR,		CSL_SYSCFG_PINMUX18_PINMUX18_23_20_SHIFT	},
	{	PINMUX18_ADDR,		CSL_SYSCFG_PINMUX18_PINMUX18_19_16_SHIFT	},
	{	PINMUX18_ADDR,		CSL_SYSCFG_PINMUX18_PINMUX18_15_12_SHIFT	},
	{	PINMUX18_ADDR,		CSL_SYSCFG_PINMUX18_PINMUX18_11_8_SHIFT	},
};

const GPIO_PINMUX_DESCRIPTOR* GPIO_PINMUX_BANK_ARRAY[NUM_GPIO_BANKS] = 
{
	GPIO_PINMUX_BANK0,
	GPIO_PINMUX_BANK1,
	GPIO_PINMUX_BANK2,
	GPIO_PINMUX_BANK3,
	GPIO_PINMUX_BANK4,
	GPIO_PINMUX_BANK5,
	GPIO_PINMUX_BANK6,
	GPIO_PINMUX_BANK7,
	GPIO_PINMUX_BANK8						// Unmapped bank. Verify datasheet before using
};


int32 GPIO_Init()
{
	if(TRANSITION_SUCCESS != PSC_EnablePeripheral(GPIO))
	{
		return -1;
	}
	return 0;
}

void GPIO_SetPinDirection(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin, GPIO_PIN_DIRECTION direction)
{
	Uint32 n_bank = 0;
	Uint32 n_pin = 0;
	volatile Uint32* reg;
	
	// Unlock KICK registers
	CSL_FINS(SysCfgRegs->KICK0R,SYSCFG_KICK0R_KICK0,KICK0R_UNLOCK);
	CSL_FINS(SysCfgRegs->KICK1R,SYSCFG_KICK1R_KICK1,KICK1R_UNLOCK);
	

	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		n_pin = pin + 16;
	}
	else	//even bank
	{
		n_pin = pin;
	}
	
	GpioRegs->BANK[n_bank].DIR &= ~(1 << n_pin);
	GpioRegs->BANK[n_bank].DIR |= direction << n_pin;
	
	reg = (volatile Uint32*)GPIO_PINMUX_BANK_ARRAY[bank][pin].pinmux; 
	
	*reg = (	(*reg & ~(PINMUX_MASK << GPIO_PINMUX_BANK_ARRAY[bank][pin].shift)) | 
				(	((PINMUX_SET_PIN_AS_GPIO) << GPIO_PINMUX_BANK_ARRAY[bank][pin].shift) & 
					(PINMUX_MASK << GPIO_PINMUX_BANK_ARRAY[bank][pin].shift)	)	);
	
	
}

void GPIO_SetBankDirection(GPIO_BANK_NUMBER bank, GPIO_PIN_DIRECTION direction)
{
	GPIO_SetPinDirection(bank, PIN0, direction);
	GPIO_SetPinDirection(bank, PIN1, direction);
	GPIO_SetPinDirection(bank, PIN2, direction);
	GPIO_SetPinDirection(bank, PIN3, direction);
	GPIO_SetPinDirection(bank, PIN4, direction);
	GPIO_SetPinDirection(bank, PIN5, direction);
	GPIO_SetPinDirection(bank, PIN6, direction);
	GPIO_SetPinDirection(bank, PIN7, direction);
	GPIO_SetPinDirection(bank, PIN8, direction);
	GPIO_SetPinDirection(bank, PIN9, direction);
	GPIO_SetPinDirection(bank, PIN10, direction);
	GPIO_SetPinDirection(bank, PIN11, direction);
	GPIO_SetPinDirection(bank, PIN12, direction);
	GPIO_SetPinDirection(bank, PIN13, direction);
	GPIO_SetPinDirection(bank, PIN14, direction);
	GPIO_SetPinDirection(bank, PIN15, direction);
}

void GPIO_SetGpioPin(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin)
{
	Uint32 n_bank = 0;
	Uint32 n_pin = 0;
	
	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		n_pin = pin + 16;
	}
	else	//even bank
	{
		n_pin = pin;
	}
	
	GpioRegs->BANK[n_bank].SET_DATA |= (0x00000001 << n_pin);	
}


void GPIO_WriteToGpioBank(GPIO_BANK_NUMBER bank, uint16 val)
{
	Uint32 n_bank = 0;
	Uint32 temp_val = 0;
	
	temp_val = val;
	
	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		GpioRegs->BANK[n_bank].OUT_DATA =  (GpioRegs->BANK[n_bank].OUT_DATA & 0x0000FFFF) | ((temp_val & 0x0000FFFF) << 16);
	}
	else	//even bank
	{
		GpioRegs->BANK[n_bank].OUT_DATA =  (GpioRegs->BANK[n_bank].OUT_DATA & 0xFFFF0000) | (temp_val & 0x0000FFFF);
	}
}

void GPIO_ClearGpioPin(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin)
{
	Uint32 n_bank = 0;
	Uint32 n_pin = 0;
	
	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		n_pin = pin + 16;
	}
	else	//even bank
	{
		n_pin = pin;
	}
	
	GpioRegs->BANK[n_bank].CLR_DATA |= (0x00000001 << n_pin);	
}


GPIO_PIN_VALUE GPIO_ReadGpioPin(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin)
{
	Uint32 n_bank = 0;
	Uint32 n_pin = 0;
	
	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		n_pin = pin + 16;
	}
	else	//even bank
	{
		n_pin = pin;
	}
	
	if(GpioRegs->BANK[n_bank].IN_DATA & (0x00000001 << n_pin))
	{
		return ONE;
	}
	else
	{
		return ZERO;
	}
}

uint16 GPIO_ReadFromGpioBank(GPIO_BANK_NUMBER bank)
{
	Uint32 n_bank = 0;

	
	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		return ( GpioRegs->BANK[n_bank].IN_DATA >> 16 & 0x0000FFFF);
	}
	else	//even bank
	{
		return ( GpioRegs->BANK[n_bank].IN_DATA & 0x0000FFFF);
	}
}



void GPIO_EnableInterruptForGpioBank(GPIO_BANK_NUMBER bank)
{
	GpioRegs->BINTEN |= 0x00000001 << bank;
}

void GPIO_DisableInterruptForGpioBank(GPIO_BANK_NUMBER bank)
{
	GpioRegs->BINTEN &= ~(0x00000001 << bank);
}

void GPIO_EnableInterruptForGpioPin(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin, GPIO_PIN_INTERRUPT_TRIGGER trigger)
{
	uint32 n_bank = 0;
	uint32 n_pin = 0;
	
	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		n_pin = pin + 16;
	}
	else	//even bank
	{
		n_pin = pin;
	}
	
	GPIO_EnableInterruptForGpioBank(bank);
	
	switch(trigger)
	{
		case RISING_EDGE:
			GpioRegs->BANK[n_bank].SET_RIS_TRIG |= 0x00000001 << n_pin;
		break;
		case FALLING_EDGE:
			GpioRegs->BANK[n_bank].SET_FAL_TRIG |= 0x00000001 << n_pin;
		break;
		case BOTH_EDGES:
			GpioRegs->BANK[n_bank].SET_RIS_TRIG |= 0x00000001 << n_pin;
			GpioRegs->BANK[n_bank].SET_FAL_TRIG |= 0x00000001 << n_pin;
		break;
		
	}
}


void GPIO_DisableInterruptForGpioPin(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin, GPIO_PIN_INTERRUPT_TRIGGER trigger)
{
	Uint32 n_bank = 0;
	Uint32 n_pin = 0;
	
	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		n_pin = pin + 16;
	}
	else	//even bank
	{
		n_pin = pin;
	}
	
	switch(trigger)
	{
		case RISING_EDGE:
			GpioRegs->BANK[n_bank].CLR_RIS_TRIG |= 0x00000001 << n_pin;
		break;
		case FALLING_EDGE:
			GpioRegs->BANK[n_bank].CLR_FAL_TRIG |= 0x00000001 << n_pin;
		break;
		case BOTH_EDGES:
			GpioRegs->BANK[n_bank].CLR_RIS_TRIG |= 0x00000001 << n_pin;
			GpioRegs->BANK[n_bank].CLR_FAL_TRIG |= 0x00000001 << n_pin;
		break;
		
	}	
}


GPIO_PIN_INTERRUPT_FLAG GPIO_CheckInterruptFlagForGpioPin(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin)
{
	Uint32 n_bank = 0;
	Uint32 n_pin = 0;
	
	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		n_pin = pin + 16;
	}
	else	//even bank
	{
		n_pin = pin;
	}
	
	if(GpioRegs->BANK[n_bank].INTSTAT & (0x00000001 << n_pin))
	{
		return PENDING_EVENT;
	}
	else
	{
		return NO_EVENT;
	}
}


void GPIO_ClearInterruptFlagForGpioPin(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin)
{
	Uint32 n_bank = 0;
	Uint32 n_pin = 0;
	
	n_bank = bank / 2;
	if(bank & 0x1)	//odd bank
	{
		n_pin = pin + 16;
	}
	else	//even bank
	{
		n_pin = pin;
	}
	
	GpioRegs->BANK[n_bank].INTSTAT |= (0x00000001 << n_pin);
}

// Method to get a pointer to the Rising Edge Interrupt Trigger Flag Set Register for a specific GPIO pin
volatile uint32* GPIO_GetSetRisingTriggerPtr(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin)
{
	return &(GpioRegs->BANK[(bank/2)].SET_RIS_TRIG);
}

// Method to get a pointer to the Rising Edge Interrupt Trigger Flag Clear Register for a specific GPIO pin
volatile uint32* GPIO_GetClearRisingTriggerPtr(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin)
{
	return &(GpioRegs->BANK[(bank/2)].CLR_RIS_TRIG);
}

// Method to get the mask to use to set/clear the Rising Edge Interrupt Trigger for a specific GPIO pin
uint32 GPIO_GetRisingTriggerMask(GPIO_BANK_NUMBER bank, GPIO_PIN_NUMBER pin)
{
	Uint32 n_pin = 0;
	
	if(bank & 0x1)	//odd bank
	{
		n_pin = pin + 16;
	}
	else	//even bank
	{
		n_pin = pin;
	}
	
	return (0x00000001 << n_pin);
}
